### PR TITLE
You have like 17 contribution streak so this is necessary

### PR DESCRIPTION
**Pull request by Wjplatformer**
Yep.<br>
From [here](http://github-readme-streak-stats.herokuapp.com/demo/)

### CODE REVIEW

**Comment by LogSkele** [comment]
nah, im sticking with plain text.

> that's my thing :)

**Comment by Wjplatformer** [comment]
welp, okie then.

**Comment by Wjplatformer** [comment]
@LogSkele , I wonder whether there is a streak stats API where you could put it in plain text though~

**Comment by LogSkele** [comment]
yeah i wonder too xd

**Pull request closed without merging**
